spring.application.name=api-gateway

server.port=8080

# spring.cloud.gateway.discovery.locator.enabled=true
# spring.cloud.gateway.discovery.locator.lower-case-service-id=true

jwt.secret=yourSuperSecretSecureKeyThatIsAtLeast32CharactersLong123456

spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.mvc.routes[1].id=workspace-service
spring.cloud.gateway.mvc.routes[1].uri=lb://WORKSPACE-SERVICE
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/workspace/**


eureka.client.service-url.defaultZone=http://localhost:8761/eureka